### PR TITLE
Composable view

### PR DESCRIPTION
**Pull request by bashbunni**
## Changes made:
- [x] add example of focusing on different models in a single view with state

### CODE REVIEW

**Comment by meowgorithm** [comment]
@bashbunni this is so awesome. I'd make a few tiny adjustments:

* I'd add some padding in the boxes to make them a little bit bigger to make it super clear that two distinct blocks are being joined together horizontally.
* I'd only draw a border on the focused item to make it super clear what's in focus. With only two items, it's hard to tell which border color is the focused on. To hide the border you can set the border to [`lipgloss.HiddenBorder()`](https://pkg.go.dev/github.com/charmbracelet/lipgloss@v0.5.0#HiddenBorder) which was designed for exactly this purpose.
* I'd bind <kbd>tab</kbd> to changing focus since that's the keybinding we commonly see for this kind of thing.

**Comment by bashbunni** [comment]
Thanks so much, I'll make those changes

**Comment by Tavi3x** [comment]
Stop

**Comment by bashbunni** [comment]
Hey @meowgorithm is this spacing what you're looking for? Or should I decrease the padding on the top?
Screen Shot 2022-08-24 at 1 47 10 PM

**Comment by meowgorithm** [comment]
@bashbunni I think so. How does it feel to you?

**Comment by bashbunni** [comment]
@meowgorithm it looks better with less padding at the top. I'll push latest changes with another screenshot

**Comment by bashbunni** [comment]
Here's what that latest change looks like:
less vertical padding

**Comment by meowgorithm** [comment]
That feels great!

Last thing: I'd pad the timer readout so the UI doesn't shift when it goes from 4 characters (`1m0s`) to 3 characters (`59s`) to 2 characters (`1s`).

https://go.dev/play/p/-5kh3B98J9x

**Comment by bashbunni** [comment]
@meowgorithm done!

**Comment by meowgorithm** [comment]
Thank you! (Squash and) merge it!! 😄

**Pull request merged**
