### PR TITLE
.github: switch to using renovate batched update prs

### PR DESCRIPTION
**Pull request by paralin**
This is a suggestion to improve dependency upgrade PRs for bubbletea.

The provided renovate.json configuration batches updates into a single PR that the bot keeps up to date with the latest versions of deps.

This helps to prevent pull request spam from dependabot + PR fatigue.

Here's an example of what an upgrade PR looks like: https://github.com/aperturerobotics/controllerbus/pull/104

Also keeps the github workflow steps up to date.

### CODE REVIEW

**Comment by caarlos0** [comment]
does it work for action updates, too?

if so, I love this!

**Comment by caarlos0** [comment]
answering my own question: yes it does

**Comment by meowgorithm** [comment]
@caarlos0 and @muesli: does this one still make sense?

**Comment by caarlos0** [comment]
i think we can close this tbh, we're already using dependabot everywhere...

**Comment by meowgorithm** [comment]
Just wanted to say appreciate the PR (as always) @paralin. In this case we're sticking with our existing tooling because of the degree in which it's woven into our workflows.

**Comment by paralin** [comment]
That's fine, it was just a suggestion. That said, I still think the advantages to batched PRs are there.

**Comment by meowgorithm** [comment]
It's a fair point; will definitely keep it mind when we take a breath and reexamine our tooling.

**Pull request closed without merging**
