### PR TITLE
support multi-byte strings on Windows

### PR DESCRIPTION
**Pull request by mattn**
On Windows, it use double-byte character sets not UTF-8. So ReadFile return DBCS bytes. it should be converted to UTF-8.

### CODE REVIEW

**Comment by muesli** [comment]
Hey @mattn!

Nice seeing you over here! Your contribution looks great, but I'm a bit puzzled about the `go fmt` changes. I can't reproduce that output locally, neither with `go fmt` nor with `goimports` or `goreturns`. What tool did you use to format the sources?

If you don't mind, I could revert the formatting changes, so we can focus on reviewing the actual change.

Thanks again!

**Comment by mattn** [comment]
Ah, it seems that specification of `go fmt` changes recently. Sorry. I'll update this PR soon.

**Comment by mattn** [comment]
Hmm, at least, same result in go1.18.

**Comment by mattn** [comment]
I'll make this changes again.

**Comment by mattn** [comment]
https://github.com/golang/go/issues/51082

gofmt is changed

**Comment by muesli** [comment]
> [golang/go#51082](https://github.com/golang/go/issues/51082)
> 
> gofmt is changed

Understood! This seems to be a pending change for 1.19, tho? Can't reproduce it with 1.18.3 for what it's worth. I think we should stick to the existing format until this gofmt change is part of a stable Go release.

**Comment by mattn** [comment]
Reverted format

**Comment by mattn** [comment]
I can squash this changes. Do you want?

**Comment by muesli** [comment]
> I can squash this changes. Do you want?

Thanks, but no need to, can do that here just fine!

**Comment by meowgorithm** [comment]
Small note that this will close #393.

**Comment by meowgorithm** [comment]
Thank you so much for the contribution, @mattn. Multi-byte support is really important to us. Cheers 🍻.

**Pull request merged**
