### PR TITLE
Add commands for toggling the altscreen

### PR DESCRIPTION
**Pull request by kiyonlin**
Implement #49

### CODE REVIEW

**Comment by meowgorithm** [comment]
This is awesome, thank you so much! I made an example which exposed a few gotchas. I'll push an update to your branch in a sec.

**Comment by kiyonlin** [comment]
I think you should put 
```go
	if p.altScreenActive {
		return
	}
```
In lock area

**Comment by meowgorithm** [comment]
Yeah, you're absolutely right

**Comment by kiyonlin** [comment]
I tried p.Enter, exitMsg, enterMsg, p.Exit but enterMsg failed(the program stack). Maybe you should take a look.

**Comment by meowgorithm** [comment]
Thanks again, @kiyonlin!

**Pull request merged**
