### PR TITLE
feat(README): add eks-node-viewer to "Bubble Tea in the Wild" list 

### PR DESCRIPTION
**Pull request by Nezz7**
- add awslabs/eks-node-viewer project to "Bubble Tea in the Wild" list

### CODE REVIEW

**Comment by meowgorithm** [comment]
This looks really nice, and sorry for the delay in getting to it. Do you mind fixing the conflict? After that we'll merge _tout de suite_.

**Comment by Nezz7** [comment]
Done

**Comment by meowgorithm** [comment]
Thanks! Will merge as soon as CI finishes.

**Comment by meowgorithm** [comment]
Thanks again and sorry for the delay!

**Pull request merged**
