### PR TITLE
Add https://github.com/MicheleFiladelfia/mandelbrot-cli to Bubble Tea in the Wild

### PR DESCRIPTION
**Pull request by MicheleFiladelfia**

### CODE REVIEW

**Comment by meowgorithm** [comment]
This looks awesome. If you don’t mind, please put the entry in alphabetical order.

**Comment by MicheleFiladelfia** [comment]
thank you very much, right now I can't do another pr because I'm on vacation, could you edit this one?

**Comment by muesli** [comment]
@MicheleFiladelfia Yeah, we can do that for you. Please don't keep closing and re-opening new PRs, there's no need for that. Just push your changes to your fork and the existing PR will update automatically.

**Comment by MicheleFiladelfia** [comment]
yes, I was wrong, sorry

**Comment by muesli** [comment]
> yes, I was wrong, sorry

No worries, thank you!

**Comment by MicheleFiladelfia** [comment]
i updated my pull request

**Comment by maaslalani** [comment]
Nice work @MicheleFiladelfia! Thank you for the PR

**Pull request merged**
