### PR TITLE
fix: deadlock condition on model init panic

### LINKED ISSUE #924: Application deadlock when initial model's init panics
**Describe the bug**
With the current flow in `*Program.Run()`, the renderer isn't started until after the initial model has its `.Init()` function called. This currently causes an issue in the event that the initial model panics unexpectedly because the program is set to recover from panics, but can't finish shutting down because it's in a deadlock. I propose moving the `p.renderer.start()` to before the `p.initialModel.Init()` call in order to prevent this deadlock scenario. This will at least have the renderer start listening for a done signal on the context in the event of a panic.

I'm unsure if there are other unintended side effects from this change, but I don't see any from testing all of the examples.

**To Reproduce**
Running the code in the `Source Code` section will reproduce the issue. Instead of the expected panic being bubbled up, the app instead gets permanently stuck hanging waiting for
```go
	// Stop the renderer before acquiring the mutex to avoid a deadlock.
	r.once.Do(func() {
		r.done <- struct{}{}
	})
```
to execute.

**Source Code**
```go
package main

import tea "github.com/charmbracelet/bubbletea"

type model struct {
}

func (m model) Init() tea.Cmd {
	//TODO implement me
	panic("implement me")
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	//TODO implement me
	panic("implement me")
}

func (m model) View() string {
	//TODO implement me
	panic("implement me")
}

func main() {
	m := model{}
	if _, err := tea.NewProgram(m).Run(); err != nil {
		panic(err)
	}
}
```

**Expected behavior**
```bash
Caught panic:                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                    
implement me                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                    
Restoring terminal...   
```

**Additional context**
I have a fork with a branch created with the proposed change [here](https://github.com/eolso/bubbletea/tree/fix-init-deadlock).

### PR DESCRIPTION
**Pull request by eolso**
Fixes #924

### CODE REVIEW

**Comment by meowgorithm** [comment]
Nice, fix seems good to me. @muesli whatcha think?

**Comment by meowgorithm** [comment]
Supersedes https://github.com/charmbracelet/bubbletea/pull/905.
Fixes https://github.com/charmbracelet/bubbletea/pull/904.

**Comment by muesli** [comment]
Still have to figure out how well this integrates with our existing render context proposals. In the current `master` it seems to be a reasonable change, so I'm gonna merge this one.

**Comment by meowgorithm** [comment]
@muesli Gonna merge this one unless you feel differently. Fixes the issue in my testing, it logically makes sense to me, and it's a small adjustment to the source code.

**Comment by muesli** [comment]
Yes, still looks good to me. I'll just click the button before I forget again :smile:

**Pull request merged**
