### PR TITLE
feat: allow to suspend bubbletea programs

### LINKED ISSUE #497: bug: cannot suspend bubbletea process
In unix shells it's expected that a terminal program suspends itself when the user pressses Ctrl+Z (which sends the signal SIGTSTP to the process).

However, bubbletea disables this terminal feature which results in Ctrl+Z becoming ineffective.

In [bubbline](https://github.com/knz/bubbline), we're solving this by using [this key handler](https://github.com/knz/bubbline/blob/71919fc07ec06e1187a5a2acb28325ca7e31d04c/editline/editline.go#L825-L835).

However this is cumbersome, and should be handled inside bubbletea directly, perhaps controlled by a top level program option.

cc @muesli

### LINKED ISSUE #1053: Suspend/Resume
It would be nice to be able to support suspend and resume (aka `^z` and `fg`). I imagine we'd need to listen for the appropriate signals as well as implement `Cmd`s.

Related: https://github.com/charmbracelet/glow/issues/333

### PR DESCRIPTION
**Pull request by caarlos0**
closes #497
closes #1053

based on @knz's implementation. thanks ❤️

### CODE REVIEW

**Comment by knz** [comment]
Thank you!

**Review by knz — COMMENTED** [review]
Typo in docstring

**Comment by caarlos0** [comment]
also made the program block and wait for a `SIGCONT` after sending `SIGTSTP` ⏲️

**Review by meowgorithm — APPROVED** [review]
This is _so_ good. @knz, thanks for sharing your solve for this!

**Pull request merged**
