### PR TITLE
fix(stdin): Fix first input loss when running multiple times

### PR DESCRIPTION
**Pull request by mritd**
Fix first input loss when running multiple times

fix charmbracelet/bubbletea#24

Signed-off-by: mritd <mritd@linux.com>

### CODE REVIEW

**Comment by mritd** [comment]
@meowgorithm This PR is checkout from v0.12.2, which is convenient for other users who use v0.12.2 to use it directly 😁.

**Comment by meowgorithm** [comment]
This is now up to date with `master` (via rebase). Apologies for the force push.

**Comment by mritd** [comment]
No problem, I try to re-reference this branch in my library 😁

**Comment by meowgorithm** [comment]
Cool! If we don't reach a good conclusion on #24 in a few days I'll do a release on `master`, then another once we merge this PR.

**Comment by meowgorithm** [comment]
Hey @mritd 👋! Thanks again for contributing this PR. We've been holding off on merging it as we're concerned that the package-level variable isn't ideal. That said, we've just closed #57 which solves a similar problem by opening and closing a TTY for input. I think we can apply a similar solution here. I'll follow up in #24.

**Comment by mritd** [comment]
OK, I'll refer to code #57 to see if there are other solutions;Finally, I'm sorry I've been a little busy recently because of the Chinese New Year and all kinds of holidays.

**Comment by meowgorithm** [comment]
@mritd Oh, no worries at all. And don't feel like you need to do anything. I just wanted to let you know we're still looking at a solution and wanted you to know we're still intending to sort this one out.

**Comment by mritd** [comment]
Ok, thank you. 😁

**Comment by erikgeiser** [comment]
Here is another implementation to fix this: https://github.com/charmbracelet/bubbletea/pull/120

**Comment by meowgorithm** [comment]
Hey @mritd — just a note that this has been fixed by #120 which we just merged. So with that in mind, I'm going to close this PR. Thanks for your efforts on this one. 🍻

**Comment by meowgorithm** [comment]
This functionality is now available in `v0.16.0`.

**Pull request closed without merging**
